version: '3.3'
services:
  db:
    container_name: postgres_own_script
    image: postgres:15.1
    restart: "no"
    environment:
      - POSTGRES_USER=jOAId890*A091
      - POSTGRES_PASSWORD=baIODU09a87e91jA
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin_own_script
    image: dpage/pgadmin4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminemail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adjoAUD()A*)(D1jl)
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin/data

volumes:
  db:
    driver: local
  pgadmin:
    driver: local